CREATE TABLE test
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    CONSTRAINT pk_test PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    username   VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255),
    avatar     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO users (id, created_at, updated_at, username, password, email, avatar)
values (1,'2024-12-15 13:45:49.574338','2024-12-15 13:45:49.574338','admin','admin','admin@admin.com','admin');