CREATE TABLE note
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    note       TEXT,
    CONSTRAINT pk_note PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);

ALTER TABLE note
    ADD CONSTRAINT FK_NOTE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);


ALTER TABLE users
DROP
COLUMN id
CASCADE;

ALTER TABLE users
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

INSERT INTO note (created_at, updated_at, user_id, note, id) VALUES ('2021-07-01 00:00:00', '2021-07-01 00:00:00', 2,
                                                                     'Note 1', 1);
INSERT INTO note (created_at, updated_at, user_id, note, id) VALUES ('2021-07-01 00:00:00', '2021-07-01 00:00:00', 2,
                                                                     'Note 2', 2);