name: Docker Image CI

on:
  push:
    branches: ["main"]
permissions:
  id-token: write

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: ghcr.io/${{ github.actor }}/web03-project
  ECS_SERVICE: MY_ECS_SERVICE
  ECS_CLUSTER: MY_ECS_CLUSTER
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION
  CONTAINER_NAME: MY_CONTAINER_NAME

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.image }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x web03-backend/gradlew

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/web03-project:calico-note-service -f web03-backend/Dockerfile web03-backend/

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GHCR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push ghcr.io/${{ github.actor }}/web03-project:calico-note-service
          echo "image=ghcr.io/${{ github.actor }}/web03-project:calico-note-service" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::061051240995:role/github-aws-oicd
          aws-region: "us-east-1"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          container-name: calico-note-service-image
          image: ${{ steps.build-image.outputs }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: calico-note-service
          cluster: CalicoCluster
          wait-for-service-stability: true
