name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x web03-backend/gradlew

      - name: Run Gradle Build
        run: docker run --rm ghcr.io/${{ github.actor }}/web03-backend:latest gradle clean build --no-daemon -x test

      - name: Build Docker image
        working-directory: web03-backend
        run: |
          docker build -t app .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.actor }}/web03-backend:latest


