name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x web03-backend/gradlew

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/web03-project:calico-note-service -f web03-backend/Dockerfile web03-backend/

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.actor }}/web03-project:calico-note-service
